if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
  fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
  if [ -x /usr/bin/glib-compile-schemas ]; then
    /usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
  fi
fi
( cd usr/share/help/ca/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/ca/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/ca/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/ca/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/ca/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/ca/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/ca/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/ca/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/cs/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/cs/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/cs/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/cs/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/cs/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/cs/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/cs/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/cs/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/de/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/de/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/de/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/de/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/de/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/de/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/de/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/de/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/el/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/el/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/el/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/el/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/el/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/el/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/el/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/el/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/es/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/es/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/es/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/es/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/es/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/es/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/es/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/es/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/fr/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/fr/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/fr/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/fr/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/fr/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/fr/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/hu/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/hu/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/hu/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/hu/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/hu/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/hu/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/hu/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/hu/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/id/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/id/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/id/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/id/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/id/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/id/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/id/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/id/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/ko/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/ko/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/ko/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/ko/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/ko/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/ko/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/ko/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/ko/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/pl/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/pl/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/pl/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/pl/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/pl/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/pl/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/pt_BR/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/pt_BR/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/pt_BR/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/pt_BR/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/pt_BR/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/pt_BR/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/pt_BR/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/pt_BR/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/sv/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/sv/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/sv/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/sv/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/sv/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/sv/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/sv/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/sv/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
( cd usr/share/help/uk/lightsoff/figures ; rm -rf lightsoff.jpg )
( cd usr/share/help/uk/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.jpg lightsoff.jpg )
( cd usr/share/help/uk/lightsoff/figures ; rm -rf lightsoff.ogv )
( cd usr/share/help/uk/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff.ogv lightsoff.ogv )
( cd usr/share/help/uk/lightsoff/figures ; rm -rf lightsoff_logo.jpg )
( cd usr/share/help/uk/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lightsoff_logo.jpg lightsoff_logo.jpg )
( cd usr/share/help/uk/lightsoff/figures ; rm -rf lo1.png )
( cd usr/share/help/uk/lightsoff/figures ; ln -sf /usr/share/help/C/lightsoff/figures/lo1.png lo1.png )
